name: Daily Search Update

on:
  schedule:
    # 매일 오후 2시 (UTC+9 기준으로는 오후 2시는 UTC 05:00)
    - cron: '0 5 * * *'
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install Chrome and ChromeDriver
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
          wget -N https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION
          CHROMEDRIVER_VERSION=$(cat LATEST_RELEASE_$CHROME_VERSION)
          wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 pandas
          
      - name: Run search update
        run: python scripts/update_search_results.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/search_results.csv
          git commit -m "자동 업데이트: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
